USE [master]
GO
/****** Object:  Database [VektorelDB]    Script Date: 29.11.2025 13:27:33 ******/
CREATE DATABASE [VektorelDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VektorelDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\VektorelDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VektorelDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\VektorelDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [VektorelDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VektorelDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VektorelDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VektorelDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VektorelDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VektorelDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VektorelDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [VektorelDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VektorelDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VektorelDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VektorelDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VektorelDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VektorelDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VektorelDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VektorelDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VektorelDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VektorelDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VektorelDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VektorelDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VektorelDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VektorelDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VektorelDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VektorelDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VektorelDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VektorelDB] SET RECOVERY FULL 
GO
ALTER DATABASE [VektorelDB] SET  MULTI_USER 
GO
ALTER DATABASE [VektorelDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VektorelDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VektorelDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VektorelDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VektorelDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [VektorelDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'VektorelDB', N'ON'
GO
ALTER DATABASE [VektorelDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [VektorelDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [VektorelDB]
GO
/****** Object:  Table [dbo].[Cities]    Script Date: 29.11.2025 13:27:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cities](
	[Id] [tinyint] NOT NULL,
	[Name] [varchar](32) NOT NULL,
	[Population] [int] NULL,
	[Area] [tinyint] NULL,
 CONSTRAINT [PK_Cities] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Departments]    Script Date: 29.11.2025 13:27:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Departments](
	[Id] [tinyint] NOT NULL,
	[Name] [varchar](16) NOT NULL,
 CONSTRAINT [PK_Departments] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Persons]    Script Date: 29.11.2025 13:27:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Persons](
	[Id] [tinyint] NOT NULL,
	[Name] [varchar](32) NOT NULL,
	[BirthDate] [date] NULL,
	[CityId] [tinyint] NOT NULL,
	[DepartmentId] [tinyint] NULL,
 CONSTRAINT [PK_Persons] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Cities] ([Id], [Name], [Population], [Area]) VALUES (1, N'Kars', NULL, NULL)
GO
INSERT [dbo].[Cities] ([Id], [Name], [Population], [Area]) VALUES (2, N'Ankara', 6000000, 252)
GO
INSERT [dbo].[Cities] ([Id], [Name], [Population], [Area]) VALUES (3, N'Trabzon', 1000000, 129)
GO
INSERT [dbo].[Cities] ([Id], [Name], [Population], [Area]) VALUES (4, N'Nevşehir', 750000, 103)
GO
INSERT [dbo].[Departments] ([Id], [Name]) VALUES (1, N'Bilgi İşlem')
GO
INSERT [dbo].[Departments] ([Id], [Name]) VALUES (2, N'Finans')
GO
INSERT [dbo].[Departments] ([Id], [Name]) VALUES (3, N'Muhasebe')
GO
INSERT [dbo].[Departments] ([Id], [Name]) VALUES (4, N'İnsan Kaynakları')
GO
INSERT [dbo].[Persons] ([Id], [Name], [BirthDate], [CityId], [DepartmentId]) VALUES (1, N'Can Perk', CAST(N'1988-02-08' AS Date), 1, NULL)
GO
INSERT [dbo].[Persons] ([Id], [Name], [BirthDate], [CityId], [DepartmentId]) VALUES (2, N'Osman Ülger', CAST(N'2000-03-19' AS Date), 3, 2)
GO
INSERT [dbo].[Persons] ([Id], [Name], [BirthDate], [CityId], [DepartmentId]) VALUES (3, N'Kenan Emmiler', CAST(N'2005-11-23' AS Date), 3, NULL)
GO
INSERT [dbo].[Persons] ([Id], [Name], [BirthDate], [CityId], [DepartmentId]) VALUES (4, N'Ömer Demircioğlu', NULL, 4, NULL)
GO
INSERT [dbo].[Persons] ([Id], [Name], [BirthDate], [CityId], [DepartmentId]) VALUES (5, N'Onur Özsoy', NULL, 2, NULL)
GO
INSERT [dbo].[Persons] ([Id], [Name], [BirthDate], [CityId], [DepartmentId]) VALUES (6, N'Asya Sığınır', NULL, 4, 5)
GO
INSERT [dbo].[Persons] ([Id], [Name], [BirthDate], [CityId], [DepartmentId]) VALUES (7, N'Kübra Cömert', CAST(N'2003-10-13' AS Date), 2, 1)
GO
USE [master]
GO
ALTER DATABASE [VektorelDB] SET  READ_WRITE 
GO
